// This file consolidates all selectors into a single object for the current flow, as we have a limited number of selectors. 
// Future implementations may consider separating selectors based on their respective pages for better organization.

export const selectors = {
    usernameInput: 'input[name="username"]',
    passwordInput: 'input[name="password"]',
    submitButton: 'button[type="submit"]',
    newProfileSelect: '[data-test="newProfileSelect"]',
    individualOption: '.v-list-item',
    firstNameInput: '[data-test="crmEditProfileIndividualFirstName"]',
    lastNameInput: '[data-test="crmEditProfileIndividualLastName"]',
    actionButton: '[data-test="actionButton"]',
    profileCreate: '[data-test="profileCreate"]',
    viewFirstName: '[data-test="crmViewProfileIndividualFirstName"]',
    viewLastName: '[data-test="crmViewProfileIndividualLastName"]',
    searchFirstName: 'label.v-label',
    inputFirstName : 'input[type="text"]',
    rowWithFirstName : 'td.text-start a',
    navMenuIcon: '[data-test="navMenuIcon"]',
    allProfilesLeftNav: 'a[data-test="allProfilesLeftNav"]',
    profileAddNote: '[data-test="profileAddNote"]',
    noteLabel: '[data-test="addNoteLabel"]',
    noteParagraph : 'div.fr-element.fr-view',
    addNoteSubmit: '[data-test="addNoteSubmit"]',
    profileAddTask: '[data-test="profileAddTask"]',
    taskType: '[data-test="addTaskTaskType"]',
    addTaskProgress: '[data-test="addTaskProgress"]',
    addTaskDueDate: '[data-test="addTaskDueDate"]',
    addTaskDropDown: '.select-option',
    parent : '.v-text-field__slot',
    addTaskLabel: '[data-test="addTaskLabel"]',
    addTaskParagraph : 'div.fr-element.fr-view',
    addTaskSubmit: '[data-test="addTaskSubmit"]',
    firstNote: '.ft-widget4__item',
    taskListItem: '.v-list-item__content .ft-widget4__item.on-schedule-line',
    taskUsername: '.ft-widget4__username',
    taskText: '.ft-widget4__text',
    menuButton: '[data-test="menuBtn"] .v-icon__svg ',
    logoutLink: 'a[href*="/logout"]',
    loginAgainButton: 'a.v-btn.v-btn--has-bg.primary',
  };
  